/* ============================================================
   kgu-meal 공유 데이터 (index.html + menu-editor.html 공용)
   - DATA_VERSION: 구조 변경 시 +1 하면 옛 localStorage 무시
   - 메뉴 필드: name, cat, price, img(선택), tbd(선택: 가격 미확인)
   - 푸드코트 sub 필드: name, days(선택: 방학 로테이션 [[from,to],...]), menus
   - 식당 필드: vacation(방학 단축, 스케줄 있음) / vacUnknown(단축운영 중이나 시간 미확인)
============================================================ */
const DATA_VERSION = 5;

const DEFAULT_CAFES = [
  {
    name:'경슐랭', type:'foodcourt',
    location:'제1복지관 지하 1층', hours:'10:30 - 14:00', lastOrder:'라스트오더 13:30',
    openH:10.5, closeH:14.0, closedWeekend:true, colorHex:'#F97316',
    vacation:true, vacNote:'여름방학 단축운영 · 매장별 운영기간이 다릅니다',
    subs:[
      { name:'만권화밥', days:[['2026-06-29','2026-07-10'],['2026-08-21','2026-08-31']], menus:[
        {name:'돼지불백덮밥',      cat:'rice',   price:5500},
        {name:'소고기카레덮밥',    cat:'rice',   price:8000},
        {name:'삼겹가지덮밥',      cat:'rice',   price:7500},
        {name:'소고기가지덮밥',    cat:'rice',   price:7500},
        {name:'연어장덮밥',        cat:'rice',   price:8000},
        {name:'소고기열무비빔밥',  cat:'rice',   price:7500},
        {name:'돼껍볶음덮밥',      cat:'rice',   price:6500},
        {name:'마라소고기덮밥',    cat:'rice',   price:7500},
        {name:'큐브스테이크 카레덮밥',cat:'rice',price:8500},
        {name:'직화소고기덮밥',    cat:'rice',   price:7000},
        {name:'직화삼겹덮밥',      cat:'rice',   price:8000},
        {name:'직화제육덮밥',      cat:'rice',   price:6500},
        {name:'참치마요덮밥',      cat:'rice',   price:6500},
        {name:'매운닭갈비덮밥',    cat:'rice',   price:6000},
        {name:'간장닭갈비덮밥',    cat:'rice',   price:6000},
        {name:'소불고기덮밥',      cat:'rice',   price:7000},
        {name:'명란마요스팸참치',  cat:'rice',   price:7000},
        {name:'스팸마요덮밥',      cat:'rice',   price:6000},
        {name:'항정살꽈리볶음덮밥',cat:'rice',   price:8500},
        {name:'치즈매운불닭덮밥',  cat:'rice',   price:7500},
        {name:'치킨마요덮밥',      cat:'rice',   price:8000},
        {name:'오삼덮밥',          cat:'rice',   price:7500},
        {name:'오징어덮밥',        cat:'rice',   price:7000},
        {name:'낙지덮밥',          cat:'rice',   price:7000},
        {name:'큐브스테이크화밥',  cat:'rice',   price:8000},
        {name:'마라큐브스테이크',  cat:'rice',   price:8500},
        {name:'불맛해물짬뽕',      cat:'noodle', price:8500},
        {name:'직화해물짜장면',    cat:'noodle', price:7500},
        {name:'소고기얼큰면',      cat:'noodle', price:6000},
      ]},
      { name:'숑숑돈까스', days:[['2026-06-16','2026-06-26'],['2026-07-22','2026-07-30']], menus:[
        {name:'돈카츠 라이스커리',     cat:'cutlet', price:10500},
        {name:'통감자 라이스커리',     cat:'cutlet', price:8900},
        {name:'에비덴 라이스커리',     cat:'cutlet', price:10900},
        {name:'숑숑카츠',             cat:'cutlet', price:7900},
        {name:'양파듬뿍카츠',         cat:'cutlet', price:9500},
        {name:'두툼치즈카츠',         cat:'cutlet', price:10500},
        {name:'모둠카츠',             cat:'cutlet', price:10900},
        {name:'큐브치즈카츠1',        cat:'cutlet', price:9900},
        {name:'큐브치즈카츠2',        cat:'cutlet', price:10900},
        {name:'고구마큐브치즈카츠',   cat:'cutlet', price:10900},
        {name:'프리미엄카츠',         cat:'cutlet', price:8900},
        {name:'카츠동',               cat:'cutlet', price:7900},
        {name:'김치치즈가츠나베',     cat:'cutlet', price:8900},
        {name:'눈꽃치즈돈까스',       cat:'cutlet', price:9500},
        {name:'슈프림돈까스',         cat:'cutlet', price:8900},
        {name:'치폴레돈까스',         cat:'cutlet', price:8900},
        {name:'경양식 왕 돈까스',     cat:'cutlet', price:9500},
        {name:'김치우동',             cat:'noodle', price:6900},
        {name:'유부우동',             cat:'noodle', price:5900},
        {name:'수제어묵꼬지우동',     cat:'noodle', price:7500},
        {name:'짬뽕우동',             cat:'noodle', price:7900},
        {name:'마라우동',             cat:'noodle', price:6900},
        {name:'마라냉모밀',           cat:'noodle', price:7500},
        {name:'마제소바',             cat:'noodle', price:8500},
        {name:'알리오올리오',         cat:'noodle', price:8500},
        {name:'까르보나라',           cat:'noodle', price:8500},
        {name:'토마토파스타',         cat:'noodle', price:8500},
        {name:'로제파스타',           cat:'noodle', price:8500},
        {name:'매콤 로제 리조또볼 파스타',cat:'noodle',price:9500},
        {name:'로제떡볶이',           cat:'snack',  price:8500},
        {name:'국물떡볶이',           cat:'snack',  price:7500},
        {name:'새우튀김(2ea)',        cat:'side',   price:3000},
      ]},
      { name:'버거&타코', days:[['2026-06-16','2026-06-26'],['2026-08-11','2026-08-20']], menus:[
        {name:'고추간장 순살치킨',    cat:'chicken',price:8000},
        {name:'달콤양념 순살치킨',    cat:'chicken',price:8000},
        {name:'손바닥 치킨',          cat:'chicken',price:3800},
        {name:'순살치킨 10ea',        cat:'chicken',price:7000},
        {name:'양념치킨 순살치킨',    cat:'chicken',price:3500},
        {name:'누들떡뽀끼',           cat:'snack',  price:5900},
        {name:'짜장누들떡뽀끼',       cat:'snack',  price:6900},
        {name:'마라로제누들떡뽀끼',   cat:'snack',  price:6900},
        {name:'마라떡뽀끼',           cat:'snack',  price:7200},
        {name:'마일드비치팩',         cat:'burger', price:10500},
        {name:'핫비치팩',             cat:'burger', price:10500},
        {name:'마일드슈비팩',         cat:'burger', price:10500},
        {name:'카츠팩',               cat:'burger', price:8500},
        {name:'포커샌드',             cat:'side',   price:3600},
        {name:'리얼 치즈스틱 2ea',    cat:'side',   price:2000},
        {name:'핫치킨슬로',           cat:'side',   price:5300},
        {name:'바삭한 감자튀김',      cat:'side',   price:2200},
        {name:'양념치킨감자튀김',     cat:'side',   price:2700},
        {name:'어니언링 4ea',         cat:'side',   price:2200},
        {name:'콘 샐러드',            cat:'side',   price:1800},
        {name:'치킨너겟(6ea)',        cat:'side',   price:3000},
        {name:'폴드포크타코',         cat:'burger', price:5600},
        {name:'핫치킨타코',           cat:'burger', price:5600},
        {name:'슈프림타코',           cat:'burger', price:5600},
        {name:'비프타코',             cat:'burger', price:5300},
        {name:'비프더블베이컨치즈',   cat:'burger', price:7500},
        {name:'비프살사',             cat:'burger', price:7400},
        {name:'치즈매니아 버거',      cat:'burger', price:7200},
        {name:'마일드 슈프림버거',    cat:'burger', price:5500},
        {name:'치킨버거 마일드',      cat:'burger', price:5500},
        {name:'비프프레쉬',           cat:'burger', price:4500},
        {name:'비프치즈 마일드',      cat:'burger', price:4300},
        {name:'비프치즈 핫',          cat:'burger', price:4300},
        {name:'비프 1975',            cat:'burger', price:4300},
        {name:'비프 오리지널',        cat:'burger', price:4200},
        {name:'포크클래식 버거',      cat:'burger', price:4200},
      ]},
      { name:'위델가', days:[['2026-06-29','2026-07-10'],['2026-07-13','2026-07-21']], menus:[
        {name:'갈비탕',             cat:'soup',   price:8000, img:'images/wedelga/09_R.jpg'},
        {name:'육개장',             cat:'soup',   price:7000, img:'images/wedelga/04_L.jpg'},
        {name:'떡만두국',           cat:'soup',   price:7000, img:'images/wedelga/02_R.jpg'},
        {name:'물냉면',             cat:'noodle', price:6000, img:'images/wedelga/07_L.jpg'},
        {name:'물냉면+바싹불고기', cat:'noodle', price:8000, img:'images/wedelga/07_R.jpg'},
        {name:'비빔냉면',           cat:'noodle', price:6000, img:'images/wedelga/05_L.jpg'},
        {name:'비빔냉면+바싹불고기',cat:'noodle',price:8000, img:'images/wedelga/05_R.jpg'},
        {name:'돈육고추장짜글이',   cat:'soup',   price:7000, img:'images/wedelga/10_R.jpg'},
        {name:'돈육김치찌개',       cat:'soup',   price:6500, img:'images/wedelga/01_L.jpg'},
        {name:'돈육김치찜',         cat:'soup',   price:7500, img:'images/wedelga/11_R.jpg'},
        {name:'뚝배기불고기',       cat:'soup',   price:7000, img:'images/wedelga/09_L.jpg'},
        {name:'스팸김치찌개',       cat:'soup',   price:6500, img:'images/wedelga/01_R.jpg'},
        {name:'스팸순두부찌개',     cat:'soup',   price:6500, img:'images/wedelga/08_R.jpg'},
        {name:'바지락순두부',       cat:'soup',   price:6500, img:'images/wedelga/08_L.jpg'},
        {name:'차돌순두부찌개',     cat:'soup',   price:6500, img:'images/wedelga/00_L.jpg'},
        {name:'차돌된장찌개',       cat:'soup',   price:6500, img:'images/wedelga/04_R.jpg'},
        {name:'햄부대찌개',         cat:'soup',   price:7500, img:'images/wedelga/02_L.jpg'},
        {name:'소고기뚝밥',         cat:'rice',   price:7000, img:'images/wedelga/06_R.jpg'},
        {name:'알밥',               cat:'rice',   price:7000, img:'images/wedelga/06_L.jpg'},
        // tbd: 실제 가격 미확인 (price는 필터용 추정값, 화면에는 '가격 확인 중' 표시)
        {name:'참치김치찌개',       cat:'soup',   price:6500, tbd:true, img:'images/wedelga/11_L.jpg'},
        {name:'카레순두부찌개',     cat:'soup',   price:6500, tbd:true, img:'images/wedelga/00_R.jpg'},
        {name:'쫄면순두부찌개',     cat:'soup',   price:6500, tbd:true, img:'images/wedelga/10_L.jpg'},
        {name:'알밥김치찌개세트',   cat:'rice',   price:8500, tbd:true, img:'images/wedelga/03_L.jpg'},
        {name:'알밥순두부찌개세트', cat:'rice',   price:8500, tbd:true, img:'images/wedelga/03_R.jpg'},
      ]},
      { name:'신머이쌀국수', days:[['2026-06-29','2026-07-10'],['2026-07-31','2026-08-10']], menus:[
        {name:'베트남 전통 쌀국수',     cat:'noodle', price:5500},
        {name:'닭반마리쌀국수',          cat:'noodle',price:7500},
        {name:'닭반마리쌀국수(매운맛)',  cat:'noodle',price:8000},
        {name:'소고기 쌀국수',          cat:'noodle', price:7500},
        {name:'소고기 쌀국수(매운맛)',  cat:'noodle', price:8500},
        {name:'북부 사파 쌀국수',        cat:'noodle', price:9000},
        {name:'감자말이 새우',          cat:'side',   price:5500},
        {name:'버터플라이 새우',        cat:'side',   price:5500},
        {name:'계란 반미',              cat:'side',   price:5500},
        {name:'해물 짜조',              cat:'side',   price:5500},
        {name:'롱 춘권',                cat:'side',   price:3000},
        {name:'단팥 춘권',              cat:'side',   price:3000},
        {name:'꿔이',                   cat:'side',   price:3500},
      ]},
    ]
  },
  {
    name:'이스퀘어', type:'normal',
    location:'제2복지관 1층', hours:'07:30 - 20:30', lastOrder:'주문마감 19:30',
    openH:7.5, closeH:20.5, closedWeekend:false, colorHex:'#3B82F6',
    vacUnknown:true, // 여름방학 단축운영 중, 구체 시간 미확인

    menus:[
      // 분식·떡볶이류
      {name:'까르보 말랑떡볶이',      cat:'snack',  price:5500},
      {name:'맵달라볶이',              cat:'snack',  price:6000},
      {name:'사천짜장라볶이',          cat:'snack',  price:6500},
      {name:'로제라볶이',              cat:'snack',  price:6500},
      {name:'맵달 말랑떡볶이',         cat:'snack',  price:5000},
      {name:'사천짜장 말랑떡볶이',     cat:'snack',  price:5500},
      {name:'로제 말랑떡볶이',         cat:'snack',  price:5500},
      // 라면류
      {name:'우삼겹 짬뽕라면',         cat:'noodle', price:6500},
      {name:'냄비 신라면',             cat:'noodle', price:3500},
      {name:'치즈라면',                cat:'noodle', price:4000},
      {name:'떡만두라면',              cat:'noodle', price:4500},
      {name:'매운해장라면',            cat:'noodle', price:4500},
      {name:'얼큰순대라면',            cat:'noodle', price:5500},
      // 김밥류
      {name:'스퀘어김밥',              cat:'snack',  price:3500},
      {name:'치즈김밥',                cat:'snack',  price:4000},
      {name:'참치김밥',                cat:'snack',  price:4500},
      // 돈까스류
      {name:'치킨까스(140g)',          cat:'cutlet', price:4500},
      {name:'등심돈까스(200g)',        cat:'cutlet', price:6800},
      {name:'핵매운돈까스',            cat:'cutlet', price:7800},
      {name:'고구마치즈돈까스',        cat:'cutlet', price:7800},
      {name:'치즈돈까스',              cat:'cutlet', price:7800},
      // 사이드
      {name:'팝만두 15알',             cat:'side',   price:3000},
      {name:'소떡소떡',                cat:'side',   price:3200},
      {name:'공깃밥',                  cat:'side',   price:1000},
      // 우동류
      {name:'어묵우동',                cat:'noodle', price:5500},
      {name:'얼큰어묵우동',            cat:'noodle', price:6000},
      // 덮밥류
      {name:'제육덮밥',                cat:'rice',   price:7500},
      {name:'참치마요덮밥',            cat:'rice',   price:8000},
      {name:'치킨마유덮밥',            cat:'rice',   price:8500},
      {name:'스팸마요덮밥',            cat:'rice',   price:8000},
      // 탕·찌개류
      {name:'부대찌개',                cat:'soup',   price:8900},
      {name:'사골 떡만두국',           cat:'soup',   price:8000},
      // 냉면·막국수·소바류
      {name:'물냉면',                  cat:'noodle', price:6500},
      {name:'비빔냉면',                cat:'noodle', price:7000},
      {name:'들기름막국수',            cat:'noodle', price:7500},
      {name:'매밀소바',                cat:'noodle', price:8000},
      // 냉면 추가
      {name:'냉면 다대기',             cat:'side',   price:500},
      {name:'냉면 육수 추가',          cat:'side',   price:500},
    ]
  },
  {
    name:'샐리박스', type:'normal',
    location:'교수연구동 5층', hours:'09:00 - 18:00', lastOrder:'',
    openH:9.0, closeH:18.0, closedWeekend:true, colorHex:'#EC4899',
    vacUnknown:true, // 여름방학 단축운영 중, 구체 시간 미확인

    menus:[
      // 버거류
      {name:'샐리버거단품',            cat:'burger', price:7000},
      {name:'경기버거단품',            cat:'burger', price:9000},
      {name:'통살치킨버거단품',        cat:'burger', price:6000},
      // 샌드위치·핫도그류
      {name:'햄에그샌드위치',          cat:'western',price:3500},
      {name:'치킨샌드위치',            cat:'western',price:4000},
      {name:'크래미샌드위치',          cat:'western',price:4000},
      {name:'통새우샌드위치',          cat:'western',price:4000},
      {name:'샐리핫도그',              cat:'western',price:4500},
      // 파스타류
      {name:'토마토미트스파게티',       cat:'noodle', price:6000},
      {name:'로제스파게티',             cat:'noodle', price:7000},
      {name:'김치스파게티',             cat:'noodle', price:7000},
      {name:'크림소세지스파게티',       cat:'noodle', price:8000},
      // 분식류
      {name:'떡볶이',                  cat:'snack',  price:7000},
      {name:'어묵우동',                cat:'noodle', price:7000},
      // 볶음밥·덮밥류
      {name:'베이컨김치볶음밥',        cat:'rice',   price:6500},
      {name:'게살새우볶음밥',          cat:'rice',   price:7000},
      {name:'소불고기볶음밥',          cat:'rice',   price:7000},
      {name:'제육덮밥',                cat:'rice',   price:8000},
      {name:'돈까스',                  cat:'cutlet', price:8000},
      // 음료·카페
      {name:'아메리카노(hot)',          cat:'drink',  price:2500},
      {name:'아메리카노(ice)',          cat:'drink',  price:2500},
      {name:'카페라떼(ice)',            cat:'drink',  price:3500},
      {name:'바닐라라떼(hot)',          cat:'drink',  price:4000},
      {name:'바닐라라떼(ice)',          cat:'drink',  price:4000},
      {name:'딸기밀크스무디',           cat:'drink',  price:4000},
      {name:'망고밀크스무디',           cat:'drink',  price:4000},
      {name:'블루베리밀크스무디',       cat:'drink',  price:4000},
      {name:'녹차라떼(hot)',            cat:'drink',  price:3500},
      {name:'녹차라떼(ice)',            cat:'drink',  price:3500},
      {name:'오곡라떼(hot)',            cat:'drink',  price:4000},
      {name:'오곡라떼(ice)',            cat:'drink',  price:4000},
      {name:'허니자몽블랙티(hot)',      cat:'drink',  price:3500},
      {name:'허니자몽블랙티(ice)',      cat:'drink',  price:3500},
      {name:'아이스티(복숭아)',         cat:'drink',  price:3000},
      {name:'아샷추',                  cat:'drink',  price:3500},
      {name:'레몬티(hot)',              cat:'drink',  price:3500},
      {name:'레몬티(ice)',              cat:'drink',  price:3500},
      {name:'레몬자몽티(hot)',          cat:'drink',  price:3500},
      {name:'레몬자몽티(ice)',          cat:'drink',  price:3500},
      {name:'청귤티(hot)',              cat:'drink',  price:3500},
      {name:'청귤티(ice)',              cat:'drink',  price:3500},
      {name:'자몽에이드',              cat:'drink',  price:4000},
      {name:'레몬에이드',              cat:'drink',  price:4000},
      {name:'허니자몽블랙에이드',       cat:'drink',  price:4000},
      {name:'청귤에이드',              cat:'drink',  price:4000},
    ]
  },
];

const CAT_MAP = {
  rice:    {label:'덮밥·밥류', color:'#D97706', bg:'rgba(217,119,6,.12)', emoji:'🍚'},
  noodle:  {label:'면류',      color:'#6366F1', bg:'rgba(99,102,241,.12)', emoji:'🍜'},
  cutlet:  {label:'돈까스',    color:'#EF4444', bg:'rgba(239,68,68,.12)', emoji:'🍖'},
  soup:    {label:'탕·찌개',   color:'#059669', bg:'rgba(5,150,105,.12)', emoji:'🍲'},
  chicken: {label:'치킨류',    color:'#F59E0B', bg:'rgba(245,158,11,.12)', emoji:'🍗'},
  burger:  {label:'버거·타코', color:'#7C3AED', bg:'rgba(124,58,237,.12)', emoji:'🍔'},
  snack:   {label:'분식류',    color:'#DB2777', bg:'rgba(219,39,119,.12)', emoji:'🍢'},
  western: {label:'샌드위치',  color:'#84CC16', bg:'rgba(132,204,22,.12)', emoji:'🥪'},
  side:    {label:'사이드',    color:'#0891B2', bg:'rgba(8,145,178,.12)', emoji:'🍟'},
  drink:   {label:'음료·카페', color:'#EC4899', bg:'rgba(236,72,153,.12)', emoji:'🥤'},
};
